export const ACTION = {
  FETCH_BOOK : 'FETCH_BOOK',
  FETCH_BOOK_SUCCESS: 'FETCH_BOOK_SUCCESS',
  FETCH_BOOK_FAILURE : 'FETCH_BOOK_FAILURE',
  FETCH_COMMENTS : 'FETCH_COMMENTS',
  FETCH_COMMENTS_SUCCESS: 'FETCH_COMMENTS_SUCCESS',
  FETCH_COMMENTS_FAILURE : 'FETCH_COMMENTS_FAILURE',
  FETCH_SUGGESTIONS : 'FETCH_SUGGESTIONS',
  FETCH_SUGGESTIONS_SUCCESS: 'FETCH_SUGGESTIONS_SUCCESS',
  FETCH_SUGGESTIONS_SUCCESS : 'FETCH_SUGGESTIONS_SUCCESS'
};
